export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

// export interface FunctionMessage<T> {
//   role: "function";
//   content: string;
//   /**
//    * The name of the author of this message. name is required if role is function, and it should be the name of the function whose response is in the content. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
//    */
//   name: string;

//   /**
//    * The name and arguments of a function that should be called, as generated by the model.
//    */
//   function_call: T;
// }

export type Message = ChatMessage;
